// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b5f3f125-d5a2-4de7-a9f3-b6a50b609591";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAccelXChange();
void onAccelYChange();
void onAccelZChange();
void onTiltXChange();
void onTiltYChange();
void onWeightKgChange();
void onTareAccelChange();
void onTareWeightChange();

float accel_x;
float accel_y;
float accel_z;
float tilt_x;
float tilt_y;
float weight_kg;
bool Tare_accel;
bool Tare_weight;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(accel_x, READWRITE, ON_CHANGE, onAccelXChange);
  ArduinoCloud.addProperty(accel_y, READWRITE, ON_CHANGE, onAccelYChange);
  ArduinoCloud.addProperty(accel_z, READWRITE, ON_CHANGE, onAccelZChange);
  ArduinoCloud.addProperty(tilt_x, READWRITE, ON_CHANGE, onTiltXChange);
  ArduinoCloud.addProperty(tilt_y, READWRITE, ON_CHANGE, onTiltYChange);
  ArduinoCloud.addProperty(weight_kg, READWRITE, ON_CHANGE, onWeightKgChange);
  ArduinoCloud.addProperty(Tare_accel, READWRITE, ON_CHANGE, onTareAccelChange);
  ArduinoCloud.addProperty(Tare_weight, READWRITE, ON_CHANGE, onTareWeightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
